# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 07:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='balance',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 30, 7, 12, 43, 213925, tzinfo=utc)),
        ),
    ]
