# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20171030_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='user_destination',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_date',
            field=models.DateTimeField(),
        ),
    ]
