# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.Account'),
        ),
    ]
