# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20171030_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='balance',
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
