# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_auto_20171031_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
