# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_auto_20171031_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
