# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0018_auto_20171104_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='self.user.first_name', max_length=50),
        ),
    ]
