# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0021_remove_account_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
